# Generated by Django 3.2 on 2021-04-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210424_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='delete_flg',
            new_name='isDeleted',
        ),
    ]
