# Generated by Django 3.2 on 2021-04-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_delete_flg_todomodel_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='id',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='todo_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
