# Generated by Django 3.2 on 2021-04-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210424_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
    ]
