# Generated by Django 3.2 on 2021-04-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_todomodel_delete_flg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='delete_flg',
        ),
    ]
