# Generated by Django 3.2 on 2021-04-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_todomodel_delete_flg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='todo_id',
            new_name='todoId',
        ),
    ]
