# Generated by Django 3.2 on 2021-04-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_todo_id_todomodel_todoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='todoId',
            new_name='id',
        ),
    ]
